export enum FlashSaleSort {
  NEWEST = 'NEWEST',
  OLDEST = 'OLDEST',
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
  START_TIME_ASC = 'START_TIME_ASC',
  START_TIME_DESC = 'START_TIME_DESC',
  END_TIME_ASC = 'END_TIME_ASC',
  END_TIME_DESC = 'END_TIME_DESC',
}
