export enum OrderStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum CouponDisabledReason {
  MIN_ORDER = 'MIN_ORDER',
  SCOPE_MISMATCH = 'SCOPE_MISMATCH',
  EXPIRED = 'EXPIRED',
  USAGE_LIMIT = 'USAGE_LIMIT',
}
